name: Build Ci Manually

on:
  - workflow_dispatch
  # - push
  # - pull_request

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: |
          # 增加最大堆空间到 4096 MiB
          echo 'org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m'
          # 启用构建缓存
          echo 'org.gradle.caching=true' >> gradle.properties
          ./gradlew assemble
          ./gradlew --stop

      # 拆分文件上传
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_release
          path: app/build/outputs/apk/release
      - name: Upload debug artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_debug
          path: app/build/outputs/apk/debug
      - name: Upload build log artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_buildlog
          path: app/build/outputs/logs
      - name: Upload mapping artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_mapping
          path: app/build/outputs/mapping
