name: Build Ci Manually

on:
  - workflow_dispatch
  # - push
  # - pull_request

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest      
    steps:
      - uses: actions/checkout@v3 # 检出代码
      - name: Set up JDK 17 # 设置JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # 可以选择其他发行版，如'adoptium'
      - name: Build with Gradle
        run: |
          # 增加最大堆空间到 4096 MiB
          echo 'org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m' >> gradle.properties
          # 启用构建缓存
          echo 'org.gradle.caching=true' >> gradle.properties
          ./gradlew assemble
          ./gradlew --stop
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install JAXB Dependencies # 安装JAXB依赖
        run: |
         sudo apt-get update
         sudo apt-get install -y maven
         mvn --version
         mvn dependency:get -Dartifact=javax.xml.bind:jaxb-api:2.3.1
         mvn dependency:get -Dartifact=com.sun.xml.bind:jaxb-core:2.3.0.1
         mvn dependency:get -Dartifact=com.sun.xml.bind:jaxb-impl:2.3.0.1
      - name: Set JAXB_CLASSPATH # 设置环境变量，将JAXB依赖添加到类路径
        run: |
          echo "JAXB_CLASSPATH=$HOME/.m2/repository/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar:$HOME/.m2/repository/com/sun/xml/bind/jaxb-core/2.3.0.1/jaxb-core-2.3.0.1.jar:$HOME/.m2/repository/com/sun/xml/bind/jaxb-impl/2.3.0.1/jaxb-impl-2.3.0.1.jar" >> $GITHUB_ENV
      - name: Build with Android SDK # 构建Android项目
        run: |
          echo y | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;35.0.2"
          $ANDROID_HOME/tools/bin/sdkmanager --list
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }} # 设置JAVA_HOME环境变量
          JAXWS_CLASSPATH: ${{ env.JAXB_CLASSPATH }} # 使用之前设置的JAXB_CLASSPATH环境变量
      - name: Install Build Tools
        run: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;35.0.2"
          $ANDROID_HOME/tools/bin/sdkmanager --list
      - name: Add Build Tools to PATH
        run: |
          echo "$ANDROID_HOME/build-tools/35.0.2" >> $GITHUB_PATH
      - name: Sign Release APK
        uses: upup-company/apksigner-android@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}
          customArgs: --v1-signing-enabled,true,--v2-signing-enabled,true,--v3-signing-enabled,true,--v3.1-signing-enabled,true,--v4-signing-enabled,true,--v5-signing-enabled,true,--v5.1-signing-enabled,true
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "35.0.2"
      
      - name: Run shell
        run: |
          echo ""
      - uses: noriban/sign-android-release@v5
        name: Sign app APK
        # ID used to access action output
        id: sign_app_debug
        with:
          releaseDirectory: app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "35.0.2"
      # 拆分文件上传
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_release
          path: app/build/outputs/apk/release
      - name: Upload debug artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_debug
          path: app/build/outputs/apk/debug
      - name: Upload build log artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_buildlog
          path: app/build/outputs/logs
      - name: Upload mapping artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_mapping
          path: app/build/outputs/mapping
